# Generated by Django 3.1.7 on 2021-03-31 09:28

import actions.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('url', models.SlugField(unique=True)),
                ('habr_url', models.SlugField()),
                ('pub_date', models.DateTimeField()),
                ('categories', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('greeting_text', models.TextField(verbose_name='Текст приветствия')),
                ('start_date', models.DateTimeField(help_text='Можно указать только будущее время по МСК', validators=[actions.models.only_future], verbose_name='Следующая рассылка')),
                ('schedule_days', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)], verbose_name='Периодичность Дни')),
                ('schedule_hours', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Периодичность Часы')),
                ('channels', models.CharField(help_text='Укажите названия каналов через запятую #general, #random', max_length=255, verbose_name='Каналы')),
                ('tags', models.CharField(blank=True, help_text='Укажите названия каналов через запятую математика, python', max_length=255, verbose_name='Ключевые слова')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
