# Generated by Django 3.1.7 on 2021-03-29 17:58

import actions.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('url', models.SlugField(unique=True)),
                ('habr_url', models.SlugField()),
                ('pub_date', models.DateTimeField()),
                ('categories', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('greeting_text', models.TextField()),
                ('start_date', models.DateTimeField(validators=[actions.models.only_future])),
                ('schedule_days', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)])),
                ('schedule_hours', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('channels', models.CharField(max_length=255)),
                ('tags', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
