# Generated by Django 3.1.7 on 2021-03-26 06:02

import actions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='start_date',
            field=models.DateTimeField(validators=[actions.models.only_future]),
        ),
    ]
