# Generated by Django 3.1.7 on 2021-04-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='first_launch',
            field=models.BooleanField(default=True, help_text='При первом запуске делает рассылку первых 5 постов подходящих под условия настройки. Далее согласно настройке', verbose_name='Первый запуск'),
        ),
    ]
