# Generated by Django 3.1.7 on 2021-04-03 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_auto_20210403_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='schedule_days',
            field=models.PositiveIntegerField(default=0, help_text='Оставьте поля пустыми для отправки каждого нового поста на канале', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)], verbose_name='Периодичность Дни'),
        ),
    ]
