# Generated by Django 3.1.7 on 2021-03-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_auto_20210326_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('url', models.SlugField(unique=True)),
                ('habr_url', models.SlugField()),
                ('pub_date', models.DateTimeField()),
                ('categories', models.TextField()),
            ],
        ),
    ]
